
class Settings:
    PROJECT_NAME = "Ruffday"
    PROJECT_VERSION = "v0.0"
    BASE_DIR = "ruffday_micro"
    DETA_PROJECT_KEY_LABEL = "DETA_PROJECT_KEY"
    ADOPTIONS_DB_NAME = "adoptions"
    ORGANIZATIONS_DB_NAME = "organizations"
    DETAILS_DB_NAME = "details"
    USERS_DB_NAME = "users"
    GOOGLE_CLIENT_ID_LABEL = "GOOGLE_CLIENT_ID"
    GOOGLE_CLIENT_SECRET_LABEL = "GOOGLE_CLIENT_SECRET"
    ENVIONMENT_LABEL = "ENVIRONMENT"
